#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const skillsDir = path.join(root, 'packages', 'skills');
const reportDir = path.join(root, 'reports');
const reportPath = path.join(reportDir, 'skill-audit-summary.md');

function wordCount(text) {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function parseFrontmatter(content) {
  if (!content.startsWith('---\n')) return null;
  const end = content.indexOf('\n---', 4);
  if (end === -1) return null;
  const raw = content.slice(4, end).trim();
  const data = {};
  for (const line of raw.split('\n')) {
    const index = line.indexOf(':');
    if (index === -1) continue;
    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim().replace(/^['"]|['"]$/g, '');
    data[key] = value;
  }
  return data;
}

const dirs = (await readdir(skillsDir, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const rows = [];
let pass = 0;
let needsReview = 0;
let broken = 0;

for (const dir of dirs) {
  const file = path.join(skillsDir, dir, 'SKILL.md');
  let status = 'PASS';
  let notes = [];

  try {
    const content = await readFile(file, 'utf8');
    const fm = parseFrontmatter(content);
    const body = content.replace(/^---[\s\S]*?---\s*/, '').trim();
    if (!fm?.name) notes.push('missing name');
    if (!fm?.description) notes.push('missing description');
    if (fm?.name && fm.name !== dir) notes.push('name/folder mismatch');
    if (wordCount(body) < 40) notes.push('short body');
    if (notes.length > 0) status = 'NEEDS_REVIEW';
  } catch (error) {
    status = 'BROKEN';
    notes.push(error.message);
  }

  if (status === 'PASS') pass += 1;
  if (status === 'NEEDS_REVIEW') needsReview += 1;
  if (status === 'BROKEN') broken += 1;
  rows.push(`| ${dir} | ${status} | ${notes.join(', ') || 'ok'} |`);
}

const report = `# Skill Audit Summary\n\nGenerated by \`npm run audit:skills\`.\n\n## Summary\n\n| Metric | Count |\n|---|---:|\n| Total | ${dirs.length} |\n| PASS | ${pass} |\n| NEEDS_REVIEW | ${needsReview} |\n| BROKEN | ${broken} |\n\n## Details\n\n| Skill | Status | Notes |\n|---|---|---|\n${rows.join('\n')}\n`;

await mkdir(reportDir, { recursive: true });
await writeFile(reportPath, report, 'utf8');
console.log(`Wrote ${reportPath}`);

if (broken > 0) process.exit(1);
